"""empty message

Revision ID: ce79db9310c1
Revises: 39397252b44a
Create Date: 2024-01-12 20:59:52.941106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce79db9310c1'
down_revision: Union[str, None] = '39397252b44a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cr_character',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inserted_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cr_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cr_user',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('inserted_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='cr_user_pkey')
    )
    op.drop_table('cr_character')
    # ### end Alembic commands ###
